name = "EllipticFunctions"
uuid = "6a4e32cb-b31a-4929-85af-fb29d9a80738"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>", "Peter Simon <peter_simon@ieee.org>"]
version = "2.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Documenter = "1.1"
SpecialFunctions = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
